DEFAULT:
  SavedGames: '%USERPROFILE%\Documents\OvGME\SavedGames'
  RootFolder: '%USERPROFILE%\Documents\OvGME\RootFolder'
DCS.openbeta_server:
  packages:
  - name: Community_A-4E-C
    version: latest
    source: SavedGames
instance2:
  packages:
  - name: Community_A-4E-C
    version: 2.0.1
    source: SavedGames
