guild_id: 112233445566  # Your Discord server ID. Right click on your server and select "Copy Server ID".
use_dashboard: true     # Use the dashboard display for your node. Default is true.
chat_command_prefix: .  # The command prefix to be used for in-game chat commands. Default is "."
database:
  url: postgres://USER:PASSWORD@DB-IP:DB-PORT/DB-NAME
  pool_min: 5           # min size of the DB pool, default is 5
  pool_max: 10          # max size of the DB pool, default is 10
logging:
  loglevel: DEBUG           # loglevel, default is DEBUG
  logrotate_count: 5        # Number of logfiles to keep after rotation. Default is 5.
  logrotate_size: 10485760  # max size of a logfile, default is 10 MB
messages:
  player_username: Your player name contains invalid characters. Please change your # Default message for players with invalid usernames
    name to join our server.
  player_default_username: Please change your default player name at the top right  # Default message for players with default usernames
    of the multiplayer selection list to an individual one!
  player_banned: 'You are banned from this server. Reason: {}'                      # Default message for banned players.
filter:
  server_name: ^Special K -           # Filter to shorten your server names on many bot displays. Default is none.
  mission_name: ^Operation|_|\(.*\)   # Filter to shorten your mission names on many bot displays. Default is none.
  tag: "'^[JDS]'"                     # If your community uses specific tags, this helps with the bots automatch functionality.
opt_plugins:                          # Optional: list of optional plugins to be loaded and used by the bot
- serverstats                         # see above
- dbexporter
- motd
- greenieboard
- punishment
- slotblocking
- music
- funkman
- ovgme
- commands
- restapi
